Repository swcamp9thTeam1/backend-project-accountbook, pull requests merged in 2024-09, with the labels that each got.

#126 Feature/asset/update by accbook
  src/main/java/com/iiiiii/accountbook/asset/command/application/service/AssetService.java
  src/main/java/com/iiiiii/accountbook/asset/command/domain/aggregate/entity/Asset.java
  src/test/java/com/iiiiii/accountbook/asset/command/service/AssetServiceTests.java
Labels: enhancement

#128 자산의 잔액 합계 조회 기능 보완
  src/main/java/com/iiiiii/accountbook/asset/query/service/AssetService.java
  src/test/java/com/iiiiii/accountbook/asset/query/service/AssetServiceTests.java
Labels: enhancement

#129 FEATURE: 고정지출 내역 기입
  src/main/java/com/iiiiii/accountbook/BackendAccountbookApplication.java
  src/main/java/com/iiiiii/accountbook/accbook/command/application/service/AccbookService.java
  src/main/java/com/iiiiii/accountbook/regular_expense/query/dto/RegularExpenseDTO.java
Labels: enhancement

#131 Fix/stores/is exist store by lat lng
  build.gradle
  src/main/java/com/iiiiii/accountbook/store/query/service/StoreService.java
Labels: enhancement

#160 Feature/group post/create post
  README.md
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/application/controller/AccGroupPostController.java
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/application/service/AccGroupPostService.java
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/application/service/AccGroupPostServiceImpl.java
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/domain/aggregate/entity/AccGroupPost.java
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/domain/aggregate/vo/RegisterAccGroupPostVO.java
  src/main/java/com/iiiiii/accountbook/acc_group_post/command/domain/repository/AccGroupPostRepository.java
  src/main/java/com/iiiiii/accountbook/config/GlobalExceptionHandler.java
  src/main/java/com/iiiiii/accountbook/exception/NotAllowedGroupRoleException.java
  src/main/java/com/iiiiii/accountbook/exception/NotGroupMemberException.java
Labels: enhancement

#164 FEATURE: 커뮤니티 게시글 등록 / 수정 / 삭제 기능 추가(첨부파일 관련 메소드는 추후 추가예정)
  src/main/java/com/iiiiii/accountbook/community/command/application/controller/CommunityController.java
  src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityService.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommnunityFileDTO.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommunityCommentDTO.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommunityPostDTO.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityComment.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityFile.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityPost.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/repository/CommunityCommentRepository.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/repository/CommunityPostRepository.java
  src/main/java/com/iiiiii/accountbook/community/query/controller/CommunityController.java
  src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityCommentDTO.java
  src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityFileDTO.java
  src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityPostDTO.java
  src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityRepository.java
  src/main/java/com/iiiiii/accountbook/community/query/service/CommunityService.java
  src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityMapper.xml
  src/test/java/com/iiiiii/accountbook/asset/command/application/service/AssetServiceTests.java
  src/test/java/com/iiiiii/accountbook/community/command/application/service/CommunityServiceTests.java
Labels: enhancement

#176 커뮤니티 게시글 첨부파일 등록 / 수정 기능 추가
  src/main/java/com/iiiiii/accountbook/community/command/application/controller/CommunityController.java
  src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityCommentService.java
  src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityFileService.java
  src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityPostService.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommnunityFileDTO.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommunityPostDTO.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityFile.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityPost.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/repository/CommunityCommentRepository.java
  src/main/java/com/iiiiii/accountbook/community/command/domain/repository/CommunityFileRepository.java
  src/test/java/com/iiiiii/accountbook/community/command/application/service/CommunityServiceTests.java
Labels: enhancement

#177 Feature/msa/accbook server
  accbook-server/build.gradle
  accbook-server/src/main/java/com/iiiiii/accbookserver/AccbookServerApplication.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/RegularExpenseServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/controller/AccbookController.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookService.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/dto/RequestRegistAccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/vo/ResponseRegExpVO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/controller/AccbookController.java
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/command/application/service/AccCommentServiceTests.java
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookServiceTests.java
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/query/service/AccbookServiceTests.java
Labels: enhancement

#178 AssetController에 modifyAssetByOut(), modifyAssetByIn() 추가
  src/main/java/com/iiiiii/accountbook/asset/command/application/controller/AssetController.java
Labels: enhancement

#180 커뮤니티 첨부파일 삭제 기능 추가
  src/main/java/com/iiiiii/accountbook/community/command/application/controller/CommunityController.java
  src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityFileService.java
  src/test/java/com/iiiiii/accountbook/community/command/application/service/CommunityServiceTests.java
Labels: enhancement

#184 Feature/stores/for msa
  main-server/src/main/java/com/iiiiii/accountbook/config/GlobalExceptionHandler.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/EmptyResultSearchStoreException.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/NotFoundStoreException.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/domain/repository/StoreReviewRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/store/command/application/controller/StoreController.java
  main-server/src/main/java/com/iiiiii/accountbook/store/command/application/service/StoreService.java
  main-server/src/main/java/com/iiiiii/accountbook/store/query/controller/StoreController.java
  main-server/src/main/java/com/iiiiii/accountbook/store/query/service/StoreService.java
  main-server/src/test/java/com/iiiiii/accountbook/store/query/service/StoreServiceTests.java
Labels: enhancement

#188 FEATURE: Gateway 서버에 Authorization 헤더 체크하는 Filter 추가 #186
  gateway-server/build.gradle
  gateway-server/src/main/java/com/iiiiii/gatewayserver/filter/AuthorizationHeaderFilter.java
  gateway-server/src/main/resources/application.yml
Labels: enhancement

#190 로그인시 body에 멤버 정보 추가
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/controller/MemberController.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/service/MemberService.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/service/MemberServiceImpl.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/domain/aggregate/dto/MemberDTO.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/vo/JwtResponseVO.java
Labels: enhancement

#191 Feature/accbook/regist msa
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/AccCategoryServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/AssetServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/RegularExpenseServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/StoreServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/controller/AccbookController.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookService.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/vo/RequestRegistStoreVO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/vo/ResponseAccCategoryVO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/vo/ResponseStoreCodeVO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/config/GlobalExceptionHandler.java
  main-server/src/main/java/com/iiiiii/accountbook/config/GlobalExceptionHandler.java
Labels: enhancement

#192 커뮤니티 첨부파일 등록 / 수정 / 삭제 테스트 코드 작성
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommnunityFileDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommunityCommentDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityComment.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityFile.java
  main-server/src/test/java/com/iiiiii/accountbook/community/command/application/service/CommunityServiceTests.java
Labels: enhancement

#195 아이디 중복 시 회원가입 방지 추가 및 로그인 시 회원 코드 출력 수정
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/controller/MemberController.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/service/MemberServiceImpl.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/security/WebSecurity.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/vo/RequestRegistMemberVO.java
Labels: enhancement

#197 회원정보 조회 부분 토큰 확인 여부 삭제
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/controller/MemberController.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/application/service/MemberServiceImpl.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/security/JwtUtil.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/vo/RequestRegistMemberVO.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/vo/ResponseFindMemberVO.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/vo/ResponseRegistMemberVO.java
Labels: enhancement

#200 Feature/accbook/regist upgrade
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/AccCategoryServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/AssetServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/RegularExpenseServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/client/StoreServiceClient.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookService.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/dto/RegistStoreDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/dto/RequestRegistAccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/config/FeignClientConfig.java
  member-server/src/main/resources/application.yml
Labels: enhancement

#201 자산 등록 Controller와 Service 수정
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/controller/AssetController.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/service/AssetService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/controller/CommunityController.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityCommentService.java
Labels: bug

#203 Feature/review/add register review vo
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/domain/aggregate/vo/RegisterReviewVO.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/application/controller/StoreReviewController.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/application/service/StoreReviewService.java
  main-server/src/test/java/com/iiiiii/accountbook/acc_group_post/command/application/service/AccGroupPostServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/acc_group_post_comment/command/application/service/AccGroupPostCommentServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/review/command/application/service/StoreReviewServiceTest.java
Labels: enhancement

#204 group, group_member, group_post_comment 관계 수정
  main-server/src/main/java/com/iiiiii/accountbook/acc_group/command/application/controller/AccGroupController.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group/command/application/service/AccGroupService.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group/query/controller/AccGroupController.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group/query/service/AccGroupService.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_member/command/application/controller/GroupMemberController.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_member/command/application/service/GroupMemberService.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_member/command/domain/repository/GroupMemberRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_member/query/service/GroupMemberService.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_post_comment/command/application/controller/AccGroupPostCommentController.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_post_comment/command/application/service/AccGroupPostCommentService.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_post_comment/command/domain/aggregate/AccGroupPostComment.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_group_post_comment/command/domain/aggregate/AccGroupPostCommentEntity.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/NotAllowedException.java
Labels: enhancement

#207 REFACTOR: 가계부 등록 리턴 URI 수정, /detail 경로 수정
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/controller/AccbookController.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/controller/AccbookController.java
Labels: enhancement

#208 자산, 가계부 카테고리 쪽 Controller와 Service 수정
  main-server/src/main/java/com/iiiiii/accountbook/acc_category/command/application/controller/AccCategoryController.java
  main-server/src/main/java/com/iiiiii/accountbook/acc_category/command/application/service/AccCategoryService.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/service/AssetService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityCommentService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityFileService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityPostService.java
Labels: bug

#209 FIX: java.util.Date -> LocalDateTime 타입으로 변경
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookDTO.java
Labels: bug

#210 자산 코드 오류 수정
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/controller/AssetController.java
Labels: bug

#212 FIX: Member code 부분 수정
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/command/domain/aggregate/entity/Member.java
Labels: enhancement

#216 Yanghyeonjin patch 1
  README.md
Labels: documentation

#215 커뮤니티 조회 기능 개발중
  main-server/src/main/java/com/iiiiii/accountbook/community/query/controller/CommunityController.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityFileDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityPostDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityFileMapper.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityPostMapper.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityCommentService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityFileService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityPostService.java
  main-server/src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityFileMapper.xml
  main-server/src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityMapper.xml
  main-server/src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityPostMapper.xml
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityServiceTests.java
Labels: enhancement

#219 Feature/stores/test code
  main-server/src/main/java/com/iiiiii/accountbook/config/GlobalExceptionHandler.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/AlreadyGeneralStoreException.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/NotAllowedRegisterGoodStoreFileTypeException.java
  main-server/src/main/java/com/iiiiii/accountbook/exception/NotFullySuccessRegisterGoodStoreException.java
  main-server/src/main/java/com/iiiiii/accountbook/store/command/application/controller/StoreController.java
  main-server/src/main/java/com/iiiiii/accountbook/store/command/application/service/StoreService.java
  main-server/src/main/java/com/iiiiii/accountbook/store/command/domain/repository/StoreRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/store/common/StoreSearchCriteria.java
  main-server/src/main/java/com/iiiiii/accountbook/store/query/controller/StoreController.java
  main-server/src/main/java/com/iiiiii/accountbook/store/query/service/StoreService.java
  main-server/src/main/resources/com/iiiiii/accountbook/store/query/repository/StoreMapper.xml
  main-server/src/test/java/com/iiiiii/accountbook/store/command/application/service/StoreServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/store/query/service/StoreServiceTests.java
  main-server/src/test/resources/images.jpeg
Labels: enhancement

#223 Feature/accbook/regist upgrade
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccCommentDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookDetailDTO.java
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/query/service/AccbookServiceTests.java
Labels: enhancement

#226 Feature/community/find
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/controller/CommunityController.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/application/service/CommunityPostScrapService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/dto/CommunityPostScrapDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityPostScrap.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/aggregate/entity/CommunityPostScrapId.java
  main-server/src/main/java/com/iiiiii/accountbook/community/command/domain/repository/CommunityPostScrapRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/controller/CommunityController.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityCommentDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityCommentMapper.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/repository/CommunityFileMapper.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityCommentService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityFileService.java
  main-server/src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityCommentMapper.xml
  main-server/src/main/resources/com/iiiiii/accountbook/community/query/repository/CommunityFileMapper.xml
  main-server/src/test/java/com/iiiiii/accountbook/community/command/application/service/CommunityServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityServiceTests.java
Labels: enhancement

#230 커뮤니티 관련 조회 Service에서 @Autowired -> 생성자 주입으로 변경
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityCommentDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityFileDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityPostDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityCommentService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityFileService.java
  main-server/src/main/java/com/iiiiii/accountbook/community/query/service/CommunityPostService.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityServiceTests.java
Labels: enhancement

#233 Feature/accbook/test command
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/controller/AccbookController.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookService.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/dto/AccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/dto/RequestRegistAccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/entity/Accbook.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/domain/aggregate/vo/ResponseAccCategoryVO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookCategoryStatsDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookDetailDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/common/InOrOutOrTransfer.java
  accbook-server/src/main/resources/com/iiiiii/accbookserver/accbook/query/repository/AccbookMapper.xml
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookServiceTests.java
  accbook-server/src/test/java/com/iiiiii/accbookserver/accbook/query/service/AccbookServiceTests.java
Labels: enhancement

#234 Jasypt로 db, token 정보 암호화 완료
  accbook-server/build.gradle
  accbook-server/src/main/java/com/iiiiii/accbookserver/config/DataSourceConfig.java
  accbook-server/src/main/resources/application.yml
  gateway-server/build.gradle
  gateway-server/src/main/java/com/iiiiii/gatewayserver/config/JasyptConfig.java
  gateway-server/src/main/java/com/iiiiii/gatewayserver/filter/AuthorizationHeaderFilter.java
  gateway-server/src/main/resources/application.yml
  main-server/build.gradle
  main-server/src/main/java/com/iiiiii/accountbook/config/DataSourceConfig.java
  main-server/src/main/resources/application.yml
  member-server/build.gradle
  member-server/src/main/java/com/iiiiii/accbooksecurity/config/DataSourceConfig.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/config/JasyptConfig.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/security/AuthenticationFilter.java
  member-server/src/main/java/com/iiiiii/accbooksecurity/member/security/JwtUtil.java
  member-server/src/main/resources/application.yml
Labels: enhancement

#235 Feature/community/test code
  main-server/src/main/java/com/iiiiii/accountbook/community/query/dto/CommunityCommentDTO.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityCommentServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityFileServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityPostServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/community/query/service/CommunityServiceTests.java
Labels: enhancement

#236 Feature/asset/related asset
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/controller/AssetController.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/application/service/AssetService.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/domain/aggregate/dto/AssetDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/domain/aggregate/entity/Asset.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/command/domain/repository/AssetRepository.java
  main-server/src/main/java/com/iiiiii/accountbook/asset/query/dto/AssetDTO.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/application/controller/StoreReviewController.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/application/service/StoreReviewService.java
  main-server/src/main/java/com/iiiiii/accountbook/review/command/domain/aggregate/vo/RegisterReviewVO.java
  main-server/src/main/resources/com/iiiiii/accountbook/asset/query/repository/AssetMapper.xml
  main-server/src/test/java/com/iiiiii/accountbook/asset/command/application/service/AssetServiceTests.java
  main-server/src/test/java/com/iiiiii/accountbook/review/command/application/service/StoreReviewServiceTest.java
Labels: enhancement

#239 Feature/accbook/add tranfer
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/command/application/service/AccbookService.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/controller/AccbookController.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/dto/AccbookMonthlyEvalDTO.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/repository/AccbookMapper.java
  accbook-server/src/main/java/com/iiiiii/accbookserver/accbook/query/service/AccbookService.java
  accbook-server/src/main/resources/com/iiiiii/accbookserver/accbook/query/repository/AccbookMapper.xml
Labels: enhancement
